### ISSUE TITLE
Visual artifacts in editor in Firefox

### ISSUE THREAD

**Issue by svick** [ashmind/TryRoslyn#67] opened 2017-03-09 14:41 UTC
Sometimes, when I type in the TryRoslyn editor, it shows the code incorrectly (even though the actual code, which is sent to Roslyn or copy-pasted is correct).

Here is how I can reproduce this:

![tryroslyn](https://cloud.githubusercontent.com/assets/287848/23754599/da785a00-04dd-11e7-9ea3-29b5b9e75821.gif)

Step by step:

1. Press Enter, behaves correctly.
2. Undo.
3. Switch branch. This step seems to be necessary to reproduce.
4. Press Enter. The editor now seems to show both the old and new code at the same time:

    ```c#
    using System;
    public class C {
        public void M() {
        }
    }   }
    }
    ```

I'm using Firefox 52.0 on Windows 10. Edge seems to work correctly.

I think this could be related to MirrorSharp, but since the repro is specific to TryRoslyn and since I don't have a simple way to test MirrorSharp on its own, I'm reporting it here.

**Comment by ashmind** [comment] 2017-03-09 19:12
@svick Thanks for the great report -- I'll try to take a look this evening.

**Comment by ashmind** [comment] 2017-04-30 23:39
@svick Does this still reproduce in latest? I had a problem reproducing it today, and I added a fix to a related issue that might also fix this.

**Comment by ashmind** [comment] 2017-05-11 12:45
Closing as cannot reproduce, but I don't mind reopening if you see it again in latest.

**Closed by ashmind** 2017-05-11 12:45 UTC
Labels: bug, cannot reproduce
